apiVersion: flows.knative.dev/v1
kind: Parallel
metadata:
  name: parallel
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
  branches:
    - filter:
        ref:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: is-even
      subscriber:
        ref:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: div2
      reply:
        ref:
          kind: Service
          apiVersion: serving.knative.dev/v1
          name: event-display
    - filter:
        ref:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: is-odd
      subscriber:
        ref:
          apiVersion: flows.knative.dev/v1
          kind: Sequence
          name: sequence
