apiVersion: flows.knative.dev/v1
kind: Sequence
metadata:
  name: sequence
  namespace: flows-example
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
  steps:
    - ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: mul3
    - ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: add1
  reply:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
